"""Type stub for the tagmap C++ extension module."""

from collections.abc import Iterable, Iterator, Mapping
from typing import Any, overload

class Object:
    data: str
    tags: set[str]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, data: str, tags: set[str]) -> None: ...

class TagMap:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, d: Mapping[str, Iterable[str]]) -> None: ...
    @overload
    def __init__(self, items: Iterable[tuple[str, Iterable[str]]]) -> None: ...
    @overload
    def __init__(
        self, keys: Iterable[str], values: Iterable[Iterable[str]]
    ) -> None: ...
    @staticmethod
    def from_dict(d: dict[str, Iterable[str]]) -> TagMap: ...
    @staticmethod
    def from_keys_values(
        keys: Iterable[str], values: Iterable[Iterable[str]]
    ) -> TagMap: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: str) -> set[str]: ...
    def __setitem__(self, key: str, tags: Iterable[str]) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def clear(self) -> None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[set[str]]: ...
    def items(self) -> list[tuple[str, set[str]]]: ...
    def tags(self) -> list[str]: ...
    def to_dict(self) -> dict[str, set[str]]: ...
    def get(self, key: str, default: Any = None) -> set[str] | Any: ...
    def setdefault(self, key: str, default: Iterable[str]) -> set[str]: ...
    def pop(self, key: str, default: Any = None) -> set[str] | Any: ...
    def popitem(self) -> tuple[str, set[str]]: ...
    def update(self, d: dict[str, Iterable[str]]) -> None: ...
    def add_tag(self, key: str, tag: str) -> None: ...
    def add_tags(self, key: str, tags: Iterable[str]) -> None: ...
    def remove_tag(self, key: str, tag: str) -> None: ...
    def discard_tag(self, key: str, tag: str) -> None: ...
    def has_tag(self, key: str, tag: str) -> bool: ...
    def find(self, tags: Iterable[str]) -> set[str]: ...
    def query(self, *tags: str) -> set[str]: ...
    def find_any(self, tags: Iterable[str]) -> set[str]: ...
    def query_any(self, *tags: str) -> set[str]: ...
    def count(self, tags: Iterable[str]) -> int: ...
    def count_any(self, tags: Iterable[str]) -> int: ...
    def retain_where(self, tags: Iterable[str]) -> list[str]: ...
    def retain_where_any(self, tags: Iterable[str]) -> list[str]: ...
    def erase(self, key: str) -> set[str]: ...
    def discard(self, key: str) -> bool: ...
    def erase_where(self, tags: Iterable[str]) -> list[str]: ...
